---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pharmacy-center
spec:
  secretName: pharmacy-center
  issuerRef:
    kind: ClusterIssuer
    name: production
  commonName: pharmacycenter.io
  dnsNames:
  - pharmacycenter.io

