---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: viktor@farcic.com
    privateKeySecretRef:
      name: production
    solvers:
      - selector: {}
        http01:
          ingress:
            class: traefik
